steps:
  - name: 'golang:1.15-buster'
    entrypoint: 'go'
    args: ['build', '.']
    env: ['GO111MODULE=on']
  - name: 'gcr.io/kaniko-project/executor:v1.3.0'
    args:
      - --destination=asia-northeast1-docker.pkg.dev/$PROJECT_ID/wli/$BRANCH_NAME:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=6h
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - set
      - image
      - deployment/wli-dep
      - srunner-dep=gcr.io/$PROJECT_ID/sinmetal/wli/$BRANCH_NAME:$COMMIT_SHA
      - --namespace=metalapps
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-b'
      - 'CLOUDSDK_COMPUTE_REGION=asia-northeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=sinmetal-tokyo-a'